name: Weekly Fitness Summary

on:
  schedule:
    - cron: '0 15 * * 4'  # Every Thursday at 15:00 (3PM) GMT
  workflow_dispatch:      # Allow manual runs too

jobs:
  run-weekly-report:
    runs-on: ubuntu-latest

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weekly crawler
        run: python crawler/weekly_crawler.py